name: proteomicsEnv
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - scipy
  - matplotlib
  - statsmodels
  - adjusttext
  - joblib
  - scikit-learn
  - imbalanced-learn
  - py-xgboost
  - infomeasure
  - seaborn
  - networkx
  - torchvision
  - torchaudio
  - pytorch
  - pyarrow
  - umap-learn
  - pip
  - git
  - pip:
      - git+https://github.com/gregversteeg/NPEET.git@8b0d9485423f74e5eb199324cf362765596538d3
