#!/usr/bin/env python3
"""
simulate_patients.py

Generate a synthetic proteomics-like dataset (patients × proteins) with:
- Correlated protein blocks via latent pathways: X = Z @ W + noise
- Binary outcome y generated by a logistic model
- A signal pool (fraction of proteins), split DISJOINTLY into:
    - main_only
    - interaction_only
    - both  (proteins with both main + interaction effects)

Design choices:
- Always holds out one random pathway (block) from ALL signal proteins so that
  at least one pathway contains no signal proteins.
- Interaction terms use centered products:
    (X1 - mean(X1)) * (X2 - mean(X2))

Outputs:
- <prefix>.csv        (X with an extra column "ards")
- <prefix>_truth.json (ground truth: signal indices, splits, betas, interaction pairs, etc.)

Example:
  python simulate_patients.py --outdir sim --p 500 --signal_rate 0.15 \
    --signal_split_main 0.5 --signal_split_inter 0.25 --signal_split_both 0.25 --seed 1
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Tuple, Dict, Any, Optional, List

import numpy as np
import pandas as pd
from scipy.special import expit


def simulate_patients(
    n: int = 250,
    p: int = 300,
    K: int = 10,
    ards_rate: float = 0.2,
    # main effects strength
    beta_signal: float = 0.9,
    beta_sd: float = 0.6,
    # interaction effects strength
    gamma_signal: float = 0.5,
    gamma_sd: float = 0.4,
    # correlation/noise
    block_strength: float = 1.0,
    noise_sd: float = 1.0,
    # signal pool size (fraction of all proteins)
    signal_rate: float = 0.15,  # e.g. 0.15 => 15% signal proteins
    # disjoint split of the signal pool (must sum <= 1)
    signal_split_main: float = 0.50,
    signal_split_inter: float = 0.25,
    signal_split_both: float = 0.25,
    seed: int = 0,
) -> Tuple[pd.DataFrame, pd.Series, Dict[str, Any]]:
    """
    Returns:
      X_df: (n × p) DataFrame with columns seq.0000, seq.0001, ...
      y_s:  (n,) Series named "ards" with values 0/1
      truth: dict with ground truth (signal groups, beta/gamma, interaction pairs, ...)
    """
    rng = np.random.default_rng(seed)

    if not (0.0 < ards_rate < 1.0):
        raise ValueError("ards_rate must be in (0, 1)")

    # validate signal shares
    if not (0.0 <= signal_rate <= 1.0):
        raise ValueError("signal_rate must be in [0, 1]")
    if min(signal_split_main, signal_split_inter, signal_split_both) < 0:
        raise ValueError("signal_split_main/inter/both must be >= 0")
    if (signal_split_main + signal_split_inter + signal_split_both) > 1.0 + 1e-12:
        raise ValueError("signal_split_main + signal_split_inter + signal_split_both must be <= 1")

    # 1) latent pathways per patient
    Z = rng.normal(0, 1, size=(n, K))  # n patients × K pathways

    # 2) assign proteins to blocks (roughly equal)
    block_id = np.repeat(np.arange(K), p // K)
    if len(block_id) < p:
        block_id = np.concatenate([block_id, rng.integers(0, K, size=p - len(block_id))])
    rng.shuffle(block_id)

    # Always hold out one pathway from ALL signal proteins (not logged by design)
    heldout_block = int(rng.integers(0, K))
    eligible_for_signal = np.where(block_id != heldout_block)[0]

    # 3) loading matrix W: each protein loads on its block
    W = np.zeros((K, p), dtype=float)
    for j in range(p):
        W[block_id[j], j] = block_strength

    # 4) protein values
    X = Z @ W + rng.normal(0, noise_sd, size=(n, p))

    # centered X for interactions: (X1-mean1)*(X2-mean2)
    Xc = X - X.mean(axis=0, keepdims=True)

    # bookkeeping defaults
    beta_vec: Optional[np.ndarray] = None
    interaction_pairs: List[Tuple[int, int]] = []
    gamma_vec: Optional[np.ndarray] = None

    # build linear predictor
    eta = np.zeros(n, dtype=float)

    # ------------------------------------------------------------
    # choose signal proteins as a fraction of all proteins
    # ------------------------------------------------------------
    n_signal = int(round(signal_rate * p))
    if n_signal > len(eligible_for_signal):
        raise ValueError(
            f"signal_rate implies n_signal={n_signal}, but only {len(eligible_for_signal)} proteins "
            "are available outside the held-out pathway."
        )

    # Signal pool (excluding held-out pathway)
    signal_idx = rng.choice(eligible_for_signal, size=n_signal, replace=False)

    # ------------------------------------------------------------
    # disjoint split of signal proteins into main/inter/both
    #   - No overlap by construction
    #   - Allocate main_only first, then inter_only, remainder goes to both
    # ------------------------------------------------------------
    n_main_only = int(round(signal_split_main * n_signal))
    n_inter_only = int(round(signal_split_inter * n_signal))
    n_both = n_signal - n_main_only - n_inter_only  # remainder -> both

    if n_both < 0:
        raise ValueError("Rounding produced negative n_both; adjust signal_split_* or signal_rate.")

    rng.shuffle(signal_idx)
    main_only_idx = signal_idx[:n_main_only]
    inter_only_idx = signal_idx[n_main_only:n_main_only + n_inter_only]
    both_idx = signal_idx[n_main_only + n_inter_only:]

    main_idx = np.concatenate([main_only_idx, both_idx]).astype(int)
    inter_idx = np.concatenate([inter_only_idx, both_idx]).astype(int)

    # ------------------------------------------------------------
    # 5) main effects: apply to main_only ∪ both
    # ------------------------------------------------------------
    if len(main_idx) > 0:
        beta_vec = rng.normal(loc=0.0, scale=beta_sd, size=len(main_idx))  # +/- allowed
        beta_vec *= beta_signal / (np.std(beta_vec) + 1e-12)               # scale overall strength
        eta += X[:, main_idx] @ beta_vec

    # ------------------------------------------------------------
    # 6) interaction effects: apply to interaction_only ∪ both
    #   - n_interactions derived from size of inter_idx (no extra parameter)
    #   - centered product: (X1-mean1)*(X2-mean2)
    # ------------------------------------------------------------
    pool = inter_idx  # always use inter signals (interaction_only ∪ both)

    if len(pool) >= 2:
        m = len(pool)
        max_pairs = m * (m - 1) // 2

        # Derived size: ~1 interaction per interaction-signal protein (safe scaling)
        n_interactions = min(max_pairs, m)

        if n_interactions > 0:
            pair_set = set()
            while len(pair_set) < n_interactions:
                j1, j2 = rng.choice(pool, size=2, replace=False)
                pair_set.add(tuple(sorted((int(j1), int(j2)))))
            interaction_pairs = list(pair_set)

            gamma_vec = rng.normal(loc=0.0, scale=gamma_sd, size=n_interactions)  # +/- allowed
            gamma_vec *= gamma_signal / (np.std(gamma_vec) + 1e-12)               # scale overall strength

            for t, (j1, j2) in enumerate(interaction_pairs):
                eta += gamma_vec[t] * (Xc[:, j1] * Xc[:, j2])

    # 7) choose intercept to match target prevalence
    b0 = 0.0
    for _ in range(50):
        probs = expit(b0 + eta)
        diff = probs.mean() - ards_rate
        b0 -= diff * 2.0

    probs = expit(b0 + eta)
    y = rng.binomial(1, probs)

    # format outputs
    X_df = pd.DataFrame(X, columns=[f"seq.{j:04d}" for j in range(p)])
    y_s = pd.Series(y.astype(int), name="ards")

    truth: Dict[str, Any] = {
        "seed": int(seed),
        "b0": float(b0),
        "prevalence": float(y_s.mean()),
        "block_id": block_id.astype(int).tolist(),
        "n_interactions": int(len(interaction_pairs)),  # NEW: explicit
        "params": dict(
            n=int(n), p=int(p), K=int(K),
            ards_rate=float(ards_rate),
            beta_signal=float(beta_signal), beta_sd=float(beta_sd),
            gamma_signal=float(gamma_signal), gamma_sd=float(gamma_sd),
            block_strength=float(block_strength), noise_sd=float(noise_sd),
            signal_rate=float(signal_rate),
            signal_split_main=float(signal_split_main),
            signal_split_inter=float(signal_split_inter),
            signal_split_both=float(signal_split_both),
        ),
        "signal_idx": signal_idx.astype(int).tolist(),
        "signal_proteins": [X_df.columns[i] for i in signal_idx],
        "main_only_idx": main_only_idx.astype(int).tolist(),
        "inter_only_idx": inter_only_idx.astype(int).tolist(),
        "both_idx": both_idx.astype(int).tolist(),
        "main_only_proteins": [X_df.columns[i] for i in main_only_idx],
        "inter_only_proteins": [X_df.columns[i] for i in inter_only_idx],
        "both_proteins": [X_df.columns[i] for i in both_idx],
        "main_idx": main_idx.astype(int).tolist(),
        "inter_idx": inter_idx.astype(int).tolist(),
        "beta_vec": None if beta_vec is None else beta_vec.astype(float).tolist(),
        "interaction_pairs": [(int(a), int(b)) for (a, b) in interaction_pairs],
        "interaction_pair_names": [(X_df.columns[a], X_df.columns[b]) for (a, b) in interaction_pairs],
        "gamma_vec": None if gamma_vec is None else gamma_vec.astype(float).tolist(),
    }

    return X_df, y_s, truth


def _parse_args() -> argparse.Namespace:
    ap = argparse.ArgumentParser(
        description="Simulate patients × proteins dataset with known ground truth."
    )

    ap.add_argument("--outdir", type=str, required=True,
                    help="Output directory to write <prefix>.csv and <prefix>_truth.json")

    # Dataset size
    ap.add_argument("--n", type=int, default=250)
    ap.add_argument("--p", type=int, default=300)
    ap.add_argument("--K", type=int, default=10)
    ap.add_argument("--ards_rate", type=float, default=0.2)

    # Main effect strength
    ap.add_argument("--beta_signal", type=float, default=0.9)
    ap.add_argument("--beta_sd", type=float, default=0.6)

    # Interaction effect strength
    ap.add_argument("--gamma_signal", type=float, default=0.5)
    ap.add_argument("--gamma_sd", type=float, default=0.4)

    # Correlation / noise
    ap.add_argument("--block_strength", type=float, default=1.0)
    ap.add_argument("--noise_sd", type=float, default=1.0)

    # Signal pool + split
    ap.add_argument("--signal_rate", type=float, default=0.15,
                    help="Fraction of proteins that are signal proteins (e.g. 0.15 = 15%)")
    ap.add_argument("--signal_split_main", type=float, default=0.50,
                    help="Fraction of signal proteins that are main-only")
    ap.add_argument("--signal_split_inter", type=float, default=0.25,
                    help="Fraction of signal proteins that are interaction-only")
    ap.add_argument("--signal_split_both", type=float, default=0.25,
                    help="Fraction of signal proteins that have both main and interaction effects")

    # Random seed + output prefix
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--prefix", type=str, default="sim",
                    help="Filename prefix. Writes <prefix>.csv and <prefix>_truth.json")

    return ap.parse_args()


def save_outputs(outdir: Path,
                 prefix: str,
                 X: pd.DataFrame,
                 y: pd.Series,
                 truth: Dict[str, Any]) -> None:
    outdir.mkdir(parents=True, exist_ok=True)

    # Save proteins + label in ONE csv
    df = X.copy()
    df["ards"] = y.values

    data_path = outdir / f"{prefix}.csv"
    df.to_csv(data_path, index=False)

    # Save ground truth separately
    truth_path = outdir / f"{prefix}_truth.json"
    with open(truth_path, "w", encoding="utf-8") as f:
        json.dump(truth, f, indent=2)

    print(f"Wrote:\n- {data_path}\n- {truth_path}")


def main() -> None:
    args = _parse_args()

    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    X, y, truth = simulate_patients(
        n=args.n,
        p=args.p,
        K=args.K,
        ards_rate=args.ards_rate,
        beta_signal=args.beta_signal,
        beta_sd=args.beta_sd,
        gamma_signal=args.gamma_signal,
        gamma_sd=args.gamma_sd,
        block_strength=args.block_strength,
        noise_sd=args.noise_sd,
        signal_rate=args.signal_rate,
        signal_split_main=args.signal_split_main,
        signal_split_inter=args.signal_split_inter,
        signal_split_both=args.signal_split_both,
        seed=args.seed,
    )

    save_outputs(outdir, args.prefix, X, y, truth)


if __name__ == "__main__":
    main()