"""Statistical helpers shared across scripts and notebooks."""

from __future__ import annotations

import math

import numpy as np


def paired_sign_flip_test(
    d: np.ndarray,
    n_permutations: int = 10000,
    rng: np.random.Generator | None = None,
) -> dict:
    """Two-sided paired sign-flip permutation test on the mean difference.

    Tests the null hypothesis that the per-split paired differences ``d_b`` are
    symmetric around zero (equivalently, that the two method labels attached
    to each paired measurement are exchangeable within a split). The
    permutation distribution is generated by independently flipping the sign
    of each ``d_b`` and recomputing the mean.

    The two-sided p-value uses the Phipson--Smyth ``+1`` correction so that
    ``p_value > 0`` and ``P(p_value <= alpha) <= alpha`` under the null.

    Parameters
    ----------
    d : np.ndarray
        1-D array of paired differences, one per split.
    n_permutations : int, default 10000
        Number of random sign-flip permutations ``R``.
    rng : numpy.random.Generator, optional
        Random generator for reproducibility. If ``None``, uses
        ``np.random.default_rng(0)``.

    Returns
    -------
    dict
        ``{"mean_diff", "p_value", "n_splits", "n_permutations"}``.
    """
    d = np.asarray(d, dtype=float).ravel()
    n_splits = int(d.size)
    if n_splits == 0:
        raise ValueError("d must contain at least one paired difference.")
    if n_permutations <= 0:
        raise ValueError(f"n_permutations must be > 0, got {n_permutations}.")

    mean_obs = float(d.mean())

    if not np.any(d):
        return {
            "mean_diff": 0.0,
            "p_value": 1.0,
            "n_splits": n_splits,
            "n_permutations": int(n_permutations),
        }

    if rng is None:
        rng = np.random.default_rng(0)

    signs = rng.integers(0, 2, size=(n_permutations, n_splits), dtype=np.int8) * 2 - 1
    perm_means = signs.astype(np.float64) @ d / n_splits
    n_extreme = int(np.sum(np.abs(perm_means) >= abs(mean_obs)))
    p_value = (1.0 + n_extreme) / (1.0 + n_permutations)

    return {
        "mean_diff": mean_obs,
        "p_value": float(p_value),
        "n_splits": n_splits,
        "n_permutations": int(n_permutations),
    }


def nadeau_bengio_se(s: float, n_splits: int, n_train: int, n_test: int) -> float:
    """Nadeau-Bengio corrected SE for repeated random subsampling.

    With B random train/test splits over the same pool of n samples, the per-split
    metrics are positively correlated through shared test patients, so the naive
    SD/sqrt(B) underestimates the SE of the mean generalisation estimate.
    Nadeau & Bengio (2003) propose

        SE_NB = s * sqrt(1/B + n_test / n_train)

    where s is the per-split sample standard deviation of the metric.

    Parameters
    ----------
    s : float
        Per-split sample standard deviation of the metric.
    n_splits : int
        Number of random splits (B).
    n_train : int
        Training-set size per split.
    n_test : int
        Test-set size per split.
    """
    if n_splits <= 0:
        raise ValueError(f"n_splits must be > 0, got {n_splits}.")
    if n_train <= 0:
        raise ValueError(f"n_train must be > 0, got {n_train}.")
    if n_test < 0:
        raise ValueError(f"n_test must be >= 0, got {n_test}.")
    return float(s) * math.sqrt(1.0 / n_splits + n_test / n_train)
